# Generated by Django 4.2.4 on 2023-09-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
